### ISSUE TITLE
[Tracking] Cleanup/remove zPIV automint related code

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1241]
Tracking issue for the removal of all zPIV aautomint related code. This is all stale code now and there is no reason to keep it.

- [x] Remove startup/config options relating to automint
- [x] Remove RPC commands for automint address functionality
- [x] Remove WalletDB methods for automint addresses
- [x] Remove routine autominting methods and constants
- [x] Remove routine automint address methods and constants

**Comment by random-zebra** [comment]
#1247 merged
