### ISSUE TITLE
Tracking: Backport upstream network encapsulation

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1374]
This is to track the backporting of various upstream PRs leading up to the goal of the P2P network encapsulation:

- [x] https://github.com/bitcoin/bitcoin/pull/7868 (Done in #1360)
- [x] https://github.com/bitcoin/bitcoin/pull/7350 (Done in #1363)
- [x] https://github.com/bitcoin/bitcoin/pull/6780 (Done in #1375)
- [x] https://github.com/bitcoin/bitcoin/pull/7257 (Done in #1376)
- [x] https://github.com/bitcoin/bitcoin/pull/7696 (Done in #1378)
- [x] https://github.com/bitcoin/bitcoin/pull/8083 (Done in #1452)
- [x] https://github.com/bitcoin/bitcoin/pull/8065 (Done in #1453)
- [x] https://github.com/bitcoin/bitcoin/pull/7181 (Done in #1542)
- [x] https://github.com/bitcoin/bitcoin/pull/6059 (Done in #1579)
- [x] https://github.com/bitcoin/bitcoin/pull/7749 (Done in #1616)
- [x] https://github.com/bitcoin/bitcoin/pull/8208 (Done in #1618)
- [x] https://github.com/bitcoin/bitcoin/pull/6556 (Done in #1638)
- [x] https://github.com/bitcoin/bitcoin/pull/8113 (Done in #1640)
- [x] https://github.com/bitcoin/bitcoin/pull/8128 (Done in #1646)
- [x] https://github.com/bitcoin/bitcoin/pull/8282 (Done in #1704)
- [x] https://github.com/bitcoin/bitcoin/pull/8466 (Done in #1812)
- [x] https://github.com/bitcoin/bitcoin/pull/8606 (Done in #1812)
- [x] https://github.com/bitcoin/bitcoin/pull/8085 (Done in #1812)
- [x] https://github.com/bitcoin/bitcoin/pull/9289 (Done in #1812)
- [x] https://github.com/bitcoin/bitcoin/pull/8740 (Done in #1812)
- [x] https://github.com/bitcoin/bitcoin/pull/8661 (Done in #1812)
