### ISSUE TITLE
[Tracking] Remove wallet 'account' API

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1706]
This is a tracking issue for the removal of the wallet's built-in 'account' API, which is clunky, error-prone, and already marked deprecated. An earlier issue (#1248) outlined the general timeline plan for this removal, this issue will track actionable changes required for each stage.

Stage 1 (v4.0.1 Jan 13 2020, *completed*):
 - [x] [RPC] Notate all account stuff as deprecated (#1251)

Stage 2 (v4.2.0 TBA, *completed* #1731):
 - [x] Rename account to label where appropriate (ref: https://github.com/bitcoin/bitcoin/pull/11536)
 - [x] Simplify getbalance implementation (ref: https://github.com/bitcoin/bitcoin/pull/9614)
 - [x] Give RPC commands more information about the RPC request (ref: https://github.com/bitcoin/bitcoin/pull/8788)
 - [x] Introduce 'label' API for wallet (ref: https://github.com/bitcoin/bitcoin/pull/12892)
 - [x] Disable account RPC functions by default. Wallet functional tests updated to use -deprecatedrpc=accounts to maintain existing behaviour (ref: https://github.com/bitcoin/bitcoin/pull/12953)
 - [x] Remove `getlabeladdress` intermediary RPC method (ref: https://github.com/bitcoin/bitcoin/pull/13060)
 - [x] Add filter option to listreceivedbyaddress (ref: https://github.com/bitcoin/bitcoin/pull/9991)
 - [x] Remove 'account' API from wallet functional tests (ref: https://github.com/bitcoin/bitcoin/pull/13075)
 - [x] Fixups from account API deprecation (ref: https://github.com/bitcoin/bitcoin/pull/13498)

Stage 3 (v5.0.0 TBA, *pending*):
 - [ ] Fully remove the 'account' API (ref: https://github.com/bitcoin/bitcoin/pull/13825 = https://github.com/bitcoin/bitcoin/commit/c9c32e6b844fc79467b7e24c6c916142a0d08484)
